### ISSUE TITLE
式が成り立たないような気がします

### ISSUE THREAD

**Issue by mitsu1119** [herumi/pairing-doc#1]
https://github.com/herumi/pairing-doc/blob/52456f9b5250251904dae71ec8f4f316808303f5/main.tex#L137-L140
e12 = -e21 になる気がするので e(x, y) = (ad - bc)e12 になると思うのですが、どうでしょう。
@elliptic-shiho さんと相談して思いました

**Comment by elliptic-shiho** [comment]
@herumi こちらセキュリティ・キャンプのゼミで読ませてもらっていて疑問点として上がったものです (確かに `e(e1, e2) = -e(e2, e1)`と思います)
周辺の記述で気になっていた箇所も含めて私の方で修正PRを投げさせてもらおうと思っていますが, レビュアー等お願いできませんでしょうか.

**Comment by herumi** [comment]
ありがとうございます。修正しました。

**Comment by elliptic-shiho** [comment]
早速の対応ありがとうございます! ただもう一点ありまして, 

https://github.com/herumi/pairing-doc/blob/f98d5d62a1ac9d38432a4791227a98073769e399/main.tex#L137

ここは `$e_{12}=-e_{21}$` ではないかと思います.

**Comment by herumi** [comment]
ありがとうございます。修正しました。

**Comment by elliptic-shiho** [comment]
修正確認しました. 対応ありがとうございました.

**Comment by mitsu1119** [comment]
対応ありがとうございます
